### ISSUE TITLE
Improve cellxgene-schema error logging

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/single-cell-curation#211]
Figure we can open a general ticket for curators to add to that for a little while for any validator requests.

Got the following error. I was able to trace it back to inadvertent NaN values in one of the obs schema fields. 
**Preferred**: The validator specifies where the NaN values are located, similar to if an invalid term is found

> Starting validation...
Traceback (most recent call last):
  File "/Users/jason/opt/anaconda3/envs/submit/bin/cellxgene-schema", line 8, in <module>
    sys.exit(schema_cli())
  File "/Users/jason/opt/anaconda3/envs/submit/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jason/opt/anaconda3/envs/submit/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/jason/opt/anaconda3/envs/submit/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jason/opt/anaconda3/envs/submit/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jason/opt/anaconda3/envs/submit/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jason/opt/anaconda3/envs/submit/lib/python3.7/site-packages/cellxgene_schema/cli.py", line 43, in schema_validate
    is_valid, _ = validate(h5ad_file, add_labels_file, verbose=verbose)
  File "/Users/jason/opt/anaconda3/envs/submit/lib/python3.7/site-packages/cellxgene_schema/validate.py", line 1253, in validate
    validator.validate_adata(h5ad_path)
  File "/Users/jason/opt/anaconda3/envs/submit/lib/python3.7/site-packages/cellxgene_schema/validate.py", line 1213, in validate_adata
    self._deep_check()
  File "/Users/jason/opt/anaconda3/envs/submit/lib/python3.7/site-packages/cellxgene_schema/validate.py", line 1170, in _deep_check
    self._validate_dataframe(component)
  File "/Users/jason/opt/anaconda3/envs/submit/lib/python3.7/site-packages/cellxgene_schema/validate.py", line 765, in _validate_dataframe
    self._validate_column(column, column_name, df_name, column_def)
  File "/Users/jason/opt/anaconda3/envs/submit/lib/python3.7/site-packages/cellxgene_schema/validate.py", line 485, in _validate_column
    term_id, column_name, column_def["curie_constraints"]
  File "/Users/jason/opt/anaconda3/envs/submit/lib/python3.7/site-packages/cellxgene_schema/validate.py", line 312, in _validate_curie
    term_id, curie_constraints["suffixes"]
  File "/Users/jason/opt/anaconda3/envs/submit/lib/python3.7/site-packages/cellxgene_schema/validate.py", line 67, in _curie_remove_suffix
    search_results = re.search(r"%s$" % suffix, term_id)
  File "/Users/jason/opt/anaconda3/envs/submit/lib/python3.7/re.py", line 185, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

**Comment by jahilton** [comment]
When submitting a term that is not in the pinned ontology, you currently get this output
>Starting validation...
WARNING: Validation of raw layer was not performed due to current errors, try again after fixing current errors.
ERROR: 'EFO:0030059' in 'assay_ontology_term_id' is not a valid ontology term id of 'EFO'.
ERROR: 'EFO:0030059' in 'assay_ontology_term_id' is not a child term id of '[['EFO:0002772', 'EFO:0010183']]'.

The second ERROR is unnecessary and actually can lead to confusion, making it more difficult to diagnose the problem

**Comment by jahilton** [comment]
Contributor ran into this error that was caused by var.feature_is_filtered being a string (`False`) rather than boolean...
>Loading dependencies
Loading validator modules
Starting validation...
Traceback (most recent call last):
  File "/home/ubuntu/cellxgene/bin/cellxgene-schema", line 8, in <module>
    sys.exit(schema_cli())
  File "/home/ubuntu/cellxgene/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/cellxgene/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/cellxgene/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/cellxgene/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/cellxgene/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/cellxgene/lib/python3.8/site-packages/cellxgene_schema/cli.py", line 50, in schema_validate
    is_valid, _, _ = validate(h5ad_file, add_labels_file, verbose=verbose)
  File "/home/ubuntu/cellxgene/lib/python3.8/site-packages/cellxgene_schema/validate.py", line 1316, in validate
    validator.validate_adata(h5ad_path)
  File "/home/ubuntu/cellxgene/lib/python3.8/site-packages/cellxgene_schema/validate.py", line 1271, in validate_adata
    self._deep_check()
  File "/home/ubuntu/cellxgene/lib/python3.8/site-packages/cellxgene_schema/validate.py", line 1228, in _deep_check
    self._validate_dataframe(component)
  File "/home/ubuntu/cellxgene/lib/python3.8/site-packages/cellxgene_schema/validate.py", line 765, in _validate_dataframe
    self._validate_column(column, column_name, df_name, column_def)
  File "/home/ubuntu/cellxgene/lib/python3.8/site-packages/cellxgene_schema/validate.py", line 455, in _validate_column
    self._validate_column_feature_is_filtered(column, column_name, df_name)
  File "/home/ubuntu/cellxgene/lib/python3.8/site-packages/cellxgene_schema/validate.py", line 387, in _validate_column_feature_is_filtered
    if sum(column) > 0:
TypeError: unsupported operand type(s) for +: 'int' and 'str'

**Comment by jychien** [comment]
The logging looks good to me! Going to close the ticket.
| Test Case                                   | Expected Result | Obtained Result                                                                                                           | Test File                 | Needs attention |
| ------------------------------------------- | --------------- | ------------------------------------------------------------------------------------------------------------------------- | ------------------------- | --------------- |
| NaN in is\_primary\_data                    | Fail validation | Failed validation<br>Logging: ERROR: Column 'is\_primary\_data' in dataframe 'obs' must be boolean, not 'object'.         | adata\_log\_nan\_pri.h5ad |                 |
| string in is\_primary\_data                 | Fail validation | Failed validation<br>Logging: ERROR: Column 'is\_primary\_data' in dataframe 'obs' must be boolean, not 'object'.         | adata\_log\_nan\_pri.h5ad |                 |
| NaN in disease\_ontology\_term\_id          | Fail validation | Failed validation<br>Logging: ERROR: Column 'disease\_ontology\_term\_id' in dataframe 'obs' must not contain NaN values. | adata\_log\_nan\_dis.h5ad |                 |
| EFO:012 in assay\_ontology\_term\_id        | Fail validation | Failed validation<br>Logging: ERROR: 'EFO:012' in 'assay\_ontology\_term\_id' is not a valid ontology term id of 'EFO'.   | adata\_log\_efo.h5ad      |                 |
| string "False" in var.feature\_is\_filtered | Fail validation | Failed validation<br>Logging: ERROR: Column 'feature\_is\_filtered' in dataframe 'var' must be boolean, not 'category'.   | adata\_log\_feature.h5ad  |
