### ISSUE TITLE
obsm embeddings must be validated 

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#590]
# Context

Placeholder until schema 4 is published. See [Update requirements for obsm embeddings](https://github.com/chanzuckerberg/single-cell-curation/issues/544). 

...

Subsequent code review also revealed that both the `cellxgene-schema CLI `and the CXG conversion process validate embeddings with some duplication, but their validation requirements are different. 

1. [Embedding validation in CXG conversion](https://github.com/chanzuckerberg/single-cell-data-portal/blame/15da6106f6742704d3233d2ab6e128b231ce7ae8/backend/layers/processing/h5ad_data_file.py#L107)
2. [Embedding validation in `cellxgene-schema CLI `](https://github.com/chanzuckerberg/single-cell-curation/blob/79a78b41414441d6f79ecf57baa57e3cea0c5eb3/cellxgene_schema_cli/cellxgene_schema/validate.py#L997)

To avoid curator dissatisfiers (part of how DP objectives are assessed), we want to ensure that validation _fast fails_ prior to the submission and upload of the dataset.

**Comment by metakuni** [comment]
Moving back to `In Progress` to reflect @joyceyan 's change on Friday.

**Comment by jahilton** [comment]
Believe the `unsigned integer` note is unnecessary as (our understanding of this is that) python isn't aware of signed vs unsigned, they'll just be read as int. If this is in correct, then help us understand so we know what to test for.

QA notes...
1. obsm key `X_` passes validation but _{suffix} MUST be at least one character long_
To recreate, take an existing .h5ad with embeddings ([this is a small valid example](https://github.com/Lattice-Data/lattice-tools/blob/CXG290-schema4validator-testing/cellxgene_resources/valid.h5ad)), read inn, then `adata.obsm['X_'] = adata.obsm['X_umap']`

2. obsm key `X_ ` passes validation but _{suffix} MUST be at least one character long_
I wouldn't think whitespace counted as a character, but maybe that's debatable.
`adata.obsm['X_ '] = adata.obsm['X_umap']`

3. obsm with _any_ np.nan fails validation but it should pass so long as _all_ are not np.nan
`coord1 = [4] + [np.nan] * (adata.obsm['X_umap'].shape[0] - 1)`
`coord2 = [-54] + [np.nan] * (adata.obsm['X_umap'].shape[0] - 1)`
`adata.obsm['X_umap'] = np.column_stack((coord1, coord2))`

4. obsm with any or all np.nan reports misleading error about infinity values.
>ERROR: adata.obsm['X_umap'] contains positive infinity or negative infinity values.

5. embeddings with type string does not fail gracefully.
`adata.obsm['X_umap'] = adata.obsm['X_umap'].astype('str')`
Error...

> Starting validation...
> Traceback (most recent call last):
>   File "/opt/anaconda3/envs/cxg4testing/bin/cellxgene-schema", line 8, in <module>
>     sys.exit(schema_cli())
>   File "/opt/anaconda3/envs/cxg4testing/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "/opt/anaconda3/envs/cxg4testing/lib/python3.9/site-packages/click/core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "/opt/anaconda3/envs/cxg4testing/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/opt/anaconda3/envs/cxg4testing/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/opt/anaconda3/envs/cxg4testing/lib/python3.9/site-packages/click/core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "/opt/anaconda3/envs/cxg4testing/lib/python3.9/site-packages/cellxgene_schema/cli.py", line 47, in schema_validate
>     is_valid, _, _ = validate(h5ad_file, add_labels_file, ignore_labels=ignore_labels, verbose=verbose)
>   File "/opt/anaconda3/envs/cxg4testing/lib/python3.9/site-packages/cellxgene_schema/validate.py", line 1220, in validate
>     validator.validate_adata(h5ad_path)
>   File "/opt/anaconda3/envs/cxg4testing/lib/python3.9/site-packages/cellxgene_schema/validate.py", line 1174, in validate_adata
>     self._deep_check()
>   File "/opt/anaconda3/envs/cxg4testing/lib/python3.9/site-packages/cellxgene_schema/validate.py", line 1135, in _deep_check
>     self._validate_embedding_dict()
>   File "/opt/anaconda3/envs/cxg4testing/lib/python3.9/site-packages/cellxgene_schema/validate.py", line 833, in _validate_embedding_dict
>     if np.isinf(value).any() or np.isnan(value).any():
> TypeError: ufunc 'isinf' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**Comment by jahilton** [comment]
Confirmed that the behavior noted above now has been corrected.

Still the lingering question about whether `unsigned integer` should be referenced in the schema and validator. @atarashansky 

And these 2 new questions arose during this round of QA...

1. The h5ad passes validation if one obsm key does not start with `X_` as long as one obsm key does
We decided that _all_ embeddings must pass validation ([discussion](https://github.com/chanzuckerberg/single-cell-curation/issues/544#issuecomment-1655844949)), and my interpretation is that the key is part of that validation. So I would expect a file with obsm keys of `X_harmony` & `umap` to fail validation.

2. The h5ad does not pass validation if one obsm key contains whitespaces (eg `X_ U M A P`)
This is not specified in the schema. @atarashansky Should the schema be updated to specify this? Or should the validator allow whitespaces?

**Comment by brianraymor** [comment]
@signechambers1 and @atarashansky - can you respond to @jahilton 's questions? I'm happy to make any subsequent edits on your behalf.

**Comment by atarashansky** [comment]
> Confirmed that the behavior noted above now has been corrected.
> 
> Still the lingering question about whether `unsigned integer` should be referenced in the schema and validator. @atarashansky
> 
> And these 2 new questions arose during this round of QA...
> 
> 1. The h5ad passes validation if one obsm key does not start with `X_` as long as one obsm key does
>    We decided that _all_ embeddings must pass validation ([discussion](https://github.com/chanzuckerberg/single-cell-curation/issues/544#issuecomment-1655844949)), and my interpretation is that the key is part of that validation. So I would expect a file with obsm keys of `X_harmony` & `umap` to fail validation.
> 2. The h5ad does not pass validation if one obsm key contains whitespaces (eg `X_ U M A P`)
>    This is not specified in the schema. @atarashansky Should the schema be updated to specify this? Or should the validator allow whitespaces?

Unsigned integer does not exist in python.

1. That is also my expectation.
2. I don't think white spaces should ever be allowed. We could explicitly encode that in the schema and validator. Alternatively, we could have the validator replace whitespaces with underscores and note this behavior in the schema. I think the latter would be a nice gesture to automatically fix cases where submitters reasonably label an embedding as "X_embedding one".

**Comment by brianraymor** [comment]
> Alternatively, we could have the validator replace whitespaces with underscores and note this behavior in the schema. I think the latter would be a nice gesture to automatically fix cases where submitters reasonably label an embedding as "X_embedding one".

I disagree. It's an **edge** case that should simply fail.  If necessary, the curators can have a conversation with the submitter about renames. We try very hard not to make the test matrix more complicated especially for edge cases.

**Comment by brianraymor** [comment]
RE `unsigned integer `, Bruce and I landed on `positive integers` in another context:

`All non-zero values MUST be positive integers stored as numpy.float32.`

**Comment by atarashansky** [comment]
> RE `unsigned integer `, Bruce and I landed on `positive integers` in another context:
> 
> `All non-zero values MUST be positive integers stored as numpy.float32.`

Why are we constraining OBSM embeddings to only contain positive integers?

**Comment by brianraymor** [comment]
RE white space - it's a slippery slope. I don't know what is allowed by the underlying data types, but often you need to worry about special characters too if you want to be extremely precise. 

And I was avoiding BNF in the schema a'la - https://www.cl.cam.ac.uk/~jac22/books/www/book/node166.html

**Comment by brianraymor** [comment]
> Why are we constraining OBSM embeddings to only contain positive integers?

Your original draft suggested unsigned integers (?), so I was responding to that point.

**Comment by atarashansky** [comment]
Not sure which original draft you're referring to. I think 

> MUST have a data type of float, integer, or unsigned integer of any precision (8, 16, 32, or 64 bits)

can be

> MUST have a data type of float or integer of any precision (8, 16, 32, or 64 bits)

**Comment by brianraymor** [comment]
@jahilton - did you successfully test **64-bit** values? 

I ask because the R language does not natively support 64 bit integers. Embeddings are included in the [seurat encoding](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/3.1.0/seurat_encoding.md#embeddings).

**Comment by jahilton** [comment]
The [valid.h5ad](https://github.com/Lattice-Data/lattice-tools/blob/CXG290-schema4validator-testing/cellxgene_resources/valid.h5ad) that we use as a base for testing has 2 embeddings - one is int64, the other is float64.
The first test in the [QA notebook](https://github.com/Lattice-Data/lattice-tools/blob/CXG290-schema4validator-testing/cellxgene_resources/cxg_4.0.0_testing/590_obsm_validation.ipynb) tests this file without alteration. It passes validation.

**Comment by brianraymor** [comment]
And is that an existing test file that has previously been successfully ingested (as a 3.1.0 dataset) and completed RDS conversion? I'm a little skittish about RDS conversions these days.

**Comment by jahilton** [comment]
RDS conversion is not part of our standard QA
But I did just submit valid.h5ad to [dev](https://cellxgene.dev.single-cell.czi.technology/collections/61ca992f-187c-4111-9af0-4af56a81dd63) & Seurat conversion was seemingly successful

**Comment by brianraymor** [comment]
`Scratches head`. OK then, thanks for humoring me. I downloaded the RDS and will take a look later based on my extremely limited knowledge of Seurat.

**Comment by brianraymor** [comment]
I was reviewing the [CXG specification](https://github.com/chanzuckerberg/single-cell-explorer/blob/main/dev_docs/cxg.md#encoding-data-with-tiledb-arrays): [**my emphasis**]

> All TileDB arrays MUST have a uint32 domain, zero-based. **All X counts and embedding coordinates SHOULD be coerced to float32, which is ample precision for visualization purposes**, and MUST be a numeric type. 

and [emb group and embedding arrays](https://github.com/chanzuckerberg/single-cell-explorer/blob/main/dev_docs/cxg.md#emb-group-and-embedding-arrays)

> A CXG MUST have a group named emb, which will contain all embeddings and MUST have at least one embedding array. Embeddings are encoded as TileDB arrays, of numeric type and shape (n_obs, >=2). The arrays MUST be a numeric type, and SHOULD be coerced to float32. Inf and NaN values MAY be used, but the semantics for these values is undefined. The TileDB array name will be assumed to be the embedding name (conventionally, embedding names in CXG are not prefixed with an X_ as they are in AnnData).

I don't quite understand the subtlety of the "SHOULD be coerced to float32".

Should embedding values in the schema simply be `numpy.float32`? CC: @bkmartinjr @atolopko-czi 

Further, I believe that the requirements must be clear that the data types are **numpy** data types and not python data types, because the data types are not equivalent:

[Overflow Errors](https://numpy.org/doc/stable/user/basics.types.html#overflow-errors)

> The behaviour of NumPy and Python integer types differs significantly for integer overflows and may confuse users expecting NumPy integers to behave similar to Python’s int. Unlike NumPy, the size of Python’s int is flexible. This means Python integers may expand to accommodate any integer and will not overflow.

[Extended Precision](https://numpy.org/doc/stable/user/basics.types.html#extended-precision)

> Python’s floating-point numbers are usually 64-bit floating-point numbers, **nearly equivalent** to np.float64. In some unusual situations it may be useful to use floating-point numbers with more precision.

**Comment by atarashansky** [comment]
> Confirmed that the behavior noted above now has been corrected.
> 
> Still the lingering question about whether `unsigned integer` should be referenced in the schema and validator. @atarashansky
> 
> And these 2 new questions arose during this round of QA...
> 
> 1. The h5ad passes validation if one obsm key does not start with `X_` as long as one obsm key does
>    We decided that _all_ embeddings must pass validation ([discussion](https://github.com/chanzuckerberg/single-cell-curation/issues/544#issuecomment-1655844949)), and my interpretation is that the key is part of that validation. So I would expect a file with obsm keys of `X_harmony` & `umap` to fail validation.
> 2. The h5ad does not pass validation if one obsm key contains whitespaces (eg `X_ U M A P`)
>    This is not specified in the schema. @atarashansky Should the schema be updated to specify this? Or should the validator allow whitespaces?

Actually, I was thinking more about point (1) - could the input AnnData's include embeddings that are not meant for visualization? If so, then we may want to use "X_" prefix as the convention to distinguish between embeddings that will be displayed in explorer from embeddings that are not meant for visualization. If that's the case, then validation should pass as long as there is at least one "X_" embedding.

@brianraymor @jahilton What do you think?

**Comment by brianraymor** [comment]
> Actually, I was thinking more about point (1) - could the input AnnData's include embeddings that are not meant for visualization? 

Yes.

> If so, then we may want to use "X_" prefix as the convention to distinguish between embeddings that will be displayed in explorer from embeddings that are not meant for visualization.

I think that the original point of the prefix. Perhaps the schema should be more clear on that point.

> If that's the case, then validation should pass as long as there is at least one "X_" embedding.

What if there are multiple "X_" embeddings and one or more fails validation? 

I'm also more generally concerned about all embeddings because all are included in the Seurat conversion.

**Comment by brianraymor** [comment]
RE the whitespace issue, I'd rewrite to:

X_{suffix} where {suffix} MUST be at least one character long and MUST NOT contain whitespace characters.

**Comment by atarashansky** [comment]
> What if there are multiple "X_" embeddings and one or more fails validation?

Right - validation should pass for all "X_" embeddings and explorer-related criteria should not apply to embeddings without the prefix

**Comment by brianraymor** [comment]
Perhaps we could separate out requirements for _generic_ embeddings vs CXG (X_) embeddings.

1. Is the shape of embeddings correct?
2. Are the values for embeddings correct?

I would be curious if anndata already enforces `1` and `2` on .write or when set. It would be nice if we didn't need to revalidate. @pablo-gar - do you know if anndata performs any validation of obsm embeddings? 

Then CXG validator would only need to enforce:
1. There must be **at least** one X_{suffix} embedding in obsm.
2. And the {suffix} for all X_ embeddings must not contain whitespace characters.

**Comment by brianraymor** [comment]
For example - https://github.com/scverse/anndata/blob/102f35a193915a1b3ca50448c397d103b21571cf/anndata/_core/anndata.py#L1894

**Comment by pablo-gar** [comment]
>  @pablo-gar - do you know if anndata performs any validation of obsm embeddings?

Unfortunately I don't

**Comment by brianraymor** [comment]
RE **MUST include at least two columns**

Hmm - anndata doesn't seem to mind if I delete a column from a valid embedding and assign an ndarray of shape (obs_n, 1).

**Comment by pablo-gar** [comment]
Under anndata that's a valid embedding, so I think that's expected. Valid embeddings can be (obs_n, X) where X is any number greater than 0. If anything I would expect anndata to validate the number or rows.

**Comment by brianraymor** [comment]
It does validate rows per my [previous comment](https://github.com/chanzuckerberg/single-cell-curation/issues/590#issuecomment-1734582056).

**Comment by jahilton** [comment]
>could the input AnnData's include embeddings that are not meant for visualization?

I have never heard of anyone request this option. I would say let's not leave that door open unless we have reason. Do we have some use case in mind?

**Comment by brianraymor** [comment]
> From this issue, I can't tell if the goal is to:

@bkmartinjr - My comments from https://github.com/chanzuckerberg/single-cell-curation/issues/544 

See [**#single-cell-data-wrangling**](https://czi-sci.slack.com/archives/C024HCSH9PT/p1680135750661479?thread_ts=1680044347.557909&cid=C024HCSH9PT) and [**#single-cell-eng**](https://czi-sci.slack.com/archives/C023Q1APASK/p1680194226881869). 

During CXG conversion, validation for [embeddings](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/3.0.0/schema.md#obsm-embeddings) **silently failed** allowing the ingestion pipeline to complete successfully. When the curator explored the dataset, an "Unexpected HTTP error" was shown because a 400 was returned by the internal [cellxgene REST API](https://github.com/chanzuckerberg/single-cell-explorer/blob/main/dev_docs/REST_API.md) due to missing embeddings in the CXG. 

Subsequent code review also revealed that both the `cellxgene-schema CLI `and the CXG conversion process validate embeddings with some duplication, but their validation requirements are different. 

1. [Embedding validation in CXG conversion](https://github.com/chanzuckerberg/single-cell-data-portal/blame/15da6106f6742704d3233d2ab6e128b231ce7ae8/backend/layers/processing/h5ad_data_file.py#L107)
2. [Embedding validation in `cellxgene-schema CLI `](https://github.com/chanzuckerberg/single-cell-curation/blob/79a78b41414441d6f79ecf57baa57e3cea0c5eb3/cellxgene_schema_cli/cellxgene_schema/validate.py#L997)

Please review and document the complete set of requirements in the schema.

**Comment by bkmartinjr** [comment]
Ah!  That clears things up.  Would I be correct to state the goal as:  ensure that all datasets have at least one Explorer-viewable embedding?

If so, IMHO the most practical path is:
* use the current Explorer requirements (e.g., numpy ndarray int/float/uint, named X_foo).  The [code already exists](https://github.com/chanzuckerberg/single-cell-data-portal/blob/6c0265366edcf73c1fb9bfde56762dd40be3365f/backend/layers/processing/h5ad_data_file.py#L108).  See comment that lays out the conditions.
* Fail if there isn't at least one obsm slot that passes the test

**Comment by pablo-gar** [comment]
> > could the input AnnData's include embeddings that are not meant for visualization?
>
> I have never heard of anyone request this option. I would say let's not leave that door open unless we have reason. Do we have some use case in mind?

Interesting you haven't heard that from contributors yet. Integrated embeddings whose dimensions haven't been reduced will almost always be > 2 columns, think NMF, latent spaces, or even the actual PCA matrix.

I think we should still allow for this specially if they are not using the "X_" prefix

**Comment by brianraymor** [comment]
> Would I be correct to state the goal as: ensure that all datasets have at least one Explorer-viewable embedding?

That would be one requirement. But if there are more than one Explorer-viewable embeddings, then all must pass or validation fails. 

I also want to ensure that non X_ embeddings do not cause RDS conversations to fail in sceasy because RDS conversion is the most brittle part of ingestion.

Once https://github.com/chanzuckerberg/single-cell/issues/420 is addressed, we'll have a fast way to see what embeddings are currently present in the corpus.

**Comment by brianraymor** [comment]
> Anything that is named X_foo and of type ndarray float/int/uint will be displayed to the user as a foo embedding. [See code here](https://github.com/chanzuckerberg/single-cell-data-portal/blob/6c0265366edcf73c1fb9bfde56762dd40be3365f/backend/layers/processing/h5ad_data_file.py#L107). Other stuff is silently ignored.

Reading:

`
is_valid = is_valid and isinstance(embedding_array, np.ndarray) and embedding_array.dtype.kind in "fiu"
`

Comprehension. 

The "fiu" is the source of [Alec's original draft](https://github.com/chanzuckerberg/single-cell-curation/issues/544#issuecomment-1648094667) - "The embedding array dtype must be a **float, integer, or unsigned integer** ..." which resulted in a [bit of confusion](https://github.com/chanzuckerberg/single-cell-curation/issues/590#issuecomment-1724595593). 


code | kind
-- | --
i | signed integer
u | unsigned integer
f | floating-point

so, the requirement could be rewritten to:

* MUST have a [`numpy.dtype.kind`](https://numpy.org/doc/stable/reference/generated/numpy.dtype.kind.html) of `"f"`, `"i"`, or `"u"`.

**Comment by brianraymor** [comment]
> Given that Explorer already applies its own criteria at run-time, and ignores anything which doesn't pass, anything stronger than "at least one embedding must pass" runs the risk of failing a legitimate dataset.

The purpose of this work is to move validation into the CLI and out of the CXG conversion where possible. 

I don't understand how that would be a legitimate dataset if:

1. X_ embeddings are defined for presentation in Explorer. There may be multiple X_ embeddings for example - spatial cases.
2. If one X_ embedding is valid and another is not, then it's not a legitimate dataset. The submitter/curator will wonder why all their embeddings are not being presented in Explorer. We want to fast fail so problems can be corrected.

**Comment by bkmartinjr** [comment]
> X_ embeddings are defined for presentation in Explorer

I think this may be part of the confusion.  `X_` embeddings are a ScanPy convention, which Explorer adopted because it was a better UX for user's who use both tools.  This means that in theory, you could have a dataset with an X_ embedding that Explorer can't fully display.

In practice this hasn't been a major concern, as Explorer protects itself from this failure and AFAIK most (all?) ScanPy-generated embeddings are viewable.  That is likely changing with spatial and new assays.

I am guessing that the drive for the CLI enhancement is to catch cases where we _expect_ the embedding to display, but it does not?  If so, we probably need some other means to explicitly notate either:
* X_ embedding which MUST pass the Explorer test, or
* X_ embeddings which MAY fail the Explorer test
I don't think we can get away with mandating that all X_ embeddings must be viewable in Explorer....

**Comment by brianraymor** [comment]
Thanks for the background, Bruce. 

Choices could be:

1. Add a notation to indicate when a specific X_ is for Explorer presentation and ignore others
2. Or Warn when there are multiple X_ embeddings and some fail Explorer requirements so the curator/submitter can correct as needed 

CC: @jahilton @signechambers1

**Comment by brianraymor** [comment]
> This means that in theory, you could have a dataset with an X_ embedding that Explorer can't fully display.

@bkmartinjr - BTW, was this behavior previously documented somewhere (other than the code)?

**Comment by bkmartinjr** [comment]
> was this behavior previously documented somewhere

No idea.  Previously there was not such a strong linkage between Explorer behavior and schema definition, so I would guess that the code _was_ the truth.

**Comment by jahilton** [comment]
Is it an option to warn when _any_ embedding (X_ or not) fail requirements and thus will not be available in Explorer?

**Comment by bkmartinjr** [comment]
> Is it an option to warn when any embedding (X_ or not) fail requirements and thus will not be available in Explorer?

Mechanically that should be quite easy to add given that the current pass/fail is well-defined in the Explorer code base.  I leave the "policy" decision to Signe/Brian.

**Comment by brianraymor** [comment]
`not X_` would never be presented in Explorer so I'm unclear about the ask. 

And could have more generic requirements per Bruce's pointer to the union:

obsm
[ndarray](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html#numpy.ndarray) | [Mapping](https://docs.python.org/3/library/collections.abc.html#collections.abc.Mapping) | [None](https://docs.python.org/3/library/constants.html#None) (default: None)
Key-indexed multi-dimensional observations annotation of length #observations. If passing a [ndarray](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html#numpy.ndarray), it needs to have a structured datatype.

**Comment by signechambers1** [comment]
I like @jahilton's suggestion. From the product perspective, I'd like any embeddings the author's want to be available in Explorer to be available and also I do not want to not create extra work for curators or submitters.

**Comment by brianraymor** [comment]
> I like @jahilton's suggestion. From the product perspective, I'd like any embeddings the author's want to be available in Explorer to be available and also I do not want to not create extra work for curators or submitters.

I'm not sure that I understand Jason's proposal or your agreement. Apologies.

Currently, an author indicates which embeddings they want in Explorer by using X_. This may fail because Explorer has additional undocumented requirements per Bruce's context.

And there may be other embeddings that do not use X_ and are currently ignored in the schema because X_ was supposed to be a presentation hint.

Is the proposal:

1. Validate ALL embeddings of type `ndarray` using CXG requirements. Warn for failures. Only present successful X_ embeddings in Explorer.
1. Validate ALL embeddings of type `ndarray` using CXG requirements. Warn for failures. Present successful X_ and not _X embeddings in Explorer (which would mean that we would need to deal with collisions like X_pca and pca).

**Comment by jahilton** [comment]
I am seeing the X_ format as just another requirement for an embedding to be used in Explorer. Not sure what makes it a 'presentation hint' vs a 'requirement'.

If an embedding is present with a key that does not start with X_, I would find it useful for the validator to surface that so that I can be aware and inform the contributor that it won't be accessible in the Explorer unless something is changed.

**Comment by signechambers1** [comment]
I don't quite understand @jahilton's comment but @brianraymor's propsal #1. "Validate ALL embeddings of type ndarray using CXG requirements. Warn for failures. Only present successful X_ embeddings in Explorer." is consistent with my thinking.

**Comment by jahilton** [comment]
>Validate ALL embeddings of type ndarray using CXG requirements. Warn for failures. Only present successful X_ embeddings in Explorer." is consistent with my thinking.

+1

**Comment by brianraymor** [comment]
> If an embedding is present with a key that does not start with X_, I would find it useful for the validator to surface

OK. So you want X_ to be considered a requirement and be included in the list of failures - like "not named X_pca and not a ndarray".

**Comment by jahilton** [comment]
>So you want X_ to be considered a requirement and be included in the list of failures - like "not named X_pca and not a ndarray".

Yes

**Comment by brianraymor** [comment]
@bkmartinjr @jahilton - does this match your understanding? 

**Summary of changes:**

X_{suffix} where {suffix} MUST be at least one character long. 

is rewritten to:

X_{suffix} where {suffix} MUST be at least one character long and MUST NOT contain whitespace characters.

---

* MUST have a data type of float, integer, or unsigned integer of any precision (8, 16, 32, or 64 bits)

is rewritten to:

* MUST have a [numpy.dtype.kind](https://numpy.org/doc/stable/reference/generated/numpy.dtype.kind.html) of "f", "i", or "u".

---

All embeddings (including non X_ keys) MUST be validated against the schema requirements. Validation errors MUST result in warning messages that include the embedding key. `"pca" is not named "X_pca"` and some such ...

And there's still a requirement for at least one X_ that passes validation - otherwise, that's a hard failure.

**Comment by bkmartinjr** [comment]
Yes, it does match my understanding.

The only nit that occurs to me is `long long` and `long double` (aka 128 bit), which the above allows (and which we are extremely unlikely to ever see in reality).  I _think_ the code handles it correctly, and certainly the schema rewrite above allows it.  The old prose was ambiguous (i.e., "any precision" alongside a list that omitted one legal value).

**Comment by jahilton** [comment]
LGTM

**Comment by joyceyan** [comment]
@jahilton Hi, this is ready for another round of QA. A few changes that were made per discussion:
- We continue to verify that there is at least one embedding key that begins with `X_`
- For embedding keys that don't start with `X_`, we raise a warning that there is a key without the `X_` prefix. Additionally, we'll run the other validations we would normally do on `X_` embedding keys, but raise these as warnings instead of errors.
- My understanding from earlier discussion was that any obsm embedding key with whitespace in it is invalid, regardless of whether or not it contains the `X_` prefix. Please let me know if this understanding is correct, or if this should only be raised as an error for `X_` prefixed keys.

**Comment by jahilton** [comment]
Looks great!
Only request is to add to the WARNING message when an embedding does not start with X_
Current: `WARNING: Embedding key in 'adata.obsm' harmony does not start with X_`
Would be great to append it with something like ` and thus will not be available in Explorer` to help the curator understand the implications of the warning

**Comment by joyceyan** [comment]
@jahilton Thanks for the feedback - I updated the warning message. I'm going to move this issue into "Ready for Staging", and I think we can close it out once we do the next release of the CLI in November. @brianraymor @signechambers1  correct me if I'm wrong about what the workflow should look like here logistically for closing out tickets.

**Comment by joyceyan** [comment]
@nayib-jose-gloria Thanks for the clarification! Closing out the ticket now.

**Comment by jahilton** [comment]
Confirmed this LGTM - [QA notebook](https://github.com/Lattice-Data/lattice-tools/blob/CXG290-schema4validator-testing/cellxgene_resources/cxg_4.0.0_testing/590_obsm_validation.ipynb) is updated
Thanks @joyceyan !
