### ISSUE TITLE
cellxgene-schema CLI erroring on numeric value in adata.uns

### ISSUE THREAD

**Issue by jychien** [chanzuckerberg/single-cell-curation#819]
I was doing some testing, and came across an error during validation when there is a numeric value in adata.uns. I am not sure how often there is a numeric value in uns,  as this was a mock h5ad.

>OverloadedDict, wrapping:
	{'title': 'Spatial transcriptomics in mouse: Puck_191223_04', 'test': 1}
With overloaded keys:
	['neighbors'].

Here is the error:

> % cellxgene-schema validate slide_seq_test.h5ad
Loading dependencies
Loading validator modules
Starting validation...
Traceback (most recent call last):
  File "/Users/jychien/miniconda3/envs/lattice/bin/cellxgene-schema", line 8, in <module>
    sys.exit(schema_cli())
  File "/Users/jychien/miniconda3/envs/lattice/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jychien/miniconda3/envs/lattice/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/jychien/miniconda3/envs/lattice/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jychien/miniconda3/envs/lattice/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jychien/miniconda3/envs/lattice/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jychien/miniconda3/envs/lattice/lib/python3.9/site-packages/cellxgene_schema/cli.py", line 47, in schema_validate
    is_valid, _, _ = validate(h5ad_file, add_labels_file, ignore_labels=ignore_labels, verbose=verbose)
  File "/Users/jychien/miniconda3/envs/lattice/lib/python3.9/site-packages/cellxgene_schema/validate.py", line 1418, in validate
    validator.validate_adata(h5ad_path, to_memory=to_memory)
  File "/Users/jychien/miniconda3/envs/lattice/lib/python3.9/site-packages/cellxgene_schema/validate.py", line 1369, in validate_adata
    self._deep_check()
  File "/Users/jychien/miniconda3/envs/lattice/lib/python3.9/site-packages/cellxgene_schema/validate.py", line 1324, in _deep_check
    self._validate_uns_dict(component)
  File "/Users/jychien/miniconda3/envs/lattice/lib/python3.9/site-packages/cellxgene_schema/validate.py", line 775, in _validate_uns_dict
    and len(value) == 0
TypeError: object of type 'numpy.int64' has no len()

**Comment by brianraymor** [comment]
The fault lies somewhere between the ambiguity in the schema requirement:

The requirement is:

> uns is a ordered dictionary with a str key. The data stored as a value for a key in uns MUST be True, False, None, or its size MUST NOT be zero.

and [its implementation](
https://github.com/chanzuckerberg/single-cell-curation/blob/b4ca077111544453bdecc55d2de06fc8e079249b/cellxgene_schema_cli/cellxgene_schema/validate.py#L772C16-L775C36) :


```
                value is not None
                and type(value) is not bool
                and not (isinstance(value, (np.bool_, np.bool)))
                and len(value) == 0
```

In this case, there seems to be an assumption that the value is always a string or an array based on the use of `len` to determine size? I guess that there was not a test case for numerics? 

I recall that there were other subtle issues such as https://github.com/chanzuckerberg/single-cell-curation/pull/803.

CC: @joyceyan @danieljhegeman

**Comment by danieljhegeman** [comment]
I'm assuming that numeric values that evaluate to zero should be permitted, as they are not technically "empty".

**Comment by brianraymor** [comment]
> I'm assuming that numeric values that evaluate to zero should be permitted, as they are not technically "empty".

Yes.
